### ISSUE TITLE
[Feature] Add scroll to top button in Contact page

### ISSUE THREAD

**Issue by bheemajayashreee** [Rakesh9100/Beautiify#1013]
### Description

There can be a back-to-top button present even in the contact page.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/112753765/e41b2f6f-e22d-43d2-b12a-9577ebd9b754)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by bheemajayashreee** [comment]
Please assign this issue to me

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
Good to add it

**Comment by Rakesh9100** [comment]
Pls complete your assigned issue first @bheemajayashreee

**Comment by Yashop181** [comment]
### Description
The "Back to Top" button is currently missing on the contact page. Adding this button will improve user navigation by allowing users to easily return to the top of the page after scrolling down.

### Tasks
- [X] Add a "Back to Top" button on the contact page.
- [X] Ensure the button only appears when the user scrolls down.

### Screenshots

#### Before:
![Before](https://github.com/user-attachments/assets/d8a4df4a-1467-4e5c-8072-db6488f80fc9)

#### After:
![After](https://github.com/user-attachments/assets/75a0e2eb-59a1-436e-9a12-19a4ae22590f)

### Additional Information
I am not a part of GSSOC'24, IWOC'24, JWOC'24, or SWOC'24, but I am eager to contribute to this project. I have checked the boxes above to be able to submit this issue. Please let me know if there is any additional information or steps required from my side.

**Comment by Rakesh9100** [comment]
You are not the part of GSSOC open source program @Yashop181

**Comment by Rakesh9100** [comment]
Are you not the part of GSSOC open source program @Yashop181

**Comment by Yashop181** [comment]
Hi @Rakesh9100,

I am not part of GSSOC'24, IWOC'24, JWOC'24, or SWOC'24, but I am eager to contribute to this project. Please let me know if there is any additional information or steps required from my side.

**Comment by Rakesh9100** [comment]
Okay, no problem, you can contribute @Yashop181
