### ISSUE TITLE
[Style] Enhance the footer with the contact details

### ISSUE THREAD

**Issue by lovelymahor** [Rakesh9100/Beautiify#1150]
### Description

Currently, our website's footer lacks essential links such as contact information and pages for Terms of Service and Privacy Policy. To improve user experience and ensure compliance, we should add these links to the footer. This enhancement will enhance navigation convenience and provide transparency regarding our policies and contact details.

**Tasks**

- Add a contact information link (email, phone, or contact form).
- Include links to the Terms of Service and Privacy Policy pages.
- Ensure links are styled and positioned appropriately in the footer.

**Expected Outcome**
Users will easily find essential information and legal policies, improving trust and accessibility on our website.

### Screenshots

![Screenshot (156)](https://github.com/Rakesh9100/Beautiify/assets/141830010/022018fd-438d-40e7-b172-d93c8c648a35)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
I think it will make better experience

**Comment by lovelymahor** [comment]
yes @Rakesh9100 Please assign it to me I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

**Comment by Rakesh9100** [comment]
Contact information can be added, but TOS and PP is not required!

Go ahead @lovelymahor
