### ISSUE TITLE
[Feature] Add Dynamic Element Tracker Cursor

### ISSUE THREAD

**Issue by Praneeth-2602** [Rakesh9100/Beautiify#1339]
### Description

A custom cursor that dynamically adapts its position, size, and shape based on user interaction with elements on the page.

### Screenshots

https://github.com/user-attachments/assets/5cb4be23-ad7c-40fb-9535-24af13670de4

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".
