### ISSUE TITLE
[Feature] <Enhancement in footer section by adding send us a  message regarding new components >

### ISSUE THREAD

**Issue by pand-coder** [Rakesh9100/Beautiify#712]
### Description

Hello PA @Rakesh9100 
I would like to create a send us a message form in the footer section
###Screenshot
![image](https://github.com/Rakesh9100/Beautiify/assets/82692757/0cc0e778-e7f6-444e-b51f-195904eeb9d1)
Typically for the new cmponents requirement from users and also i would like to add ai chat bot using api
###Record
### Tasks:
- [x] Agree to follow this project's Code of Conduct
- [x] I'm  a GSSOC'24 contributor
- [x] Work on the specified issue
Please assign me this issue to enable the required features 
Thank you :smiley:

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by rajvijay1102** [comment]
I would like to work on this project. Please assign it to me.
