### ISSUE TITLE
[Bug] Fix overlapping of scroll to top button with chatbot

### ISSUE THREAD

**Issue by karishmaaa101** [Rakesh9100/Beautiify#715]
### Description

The bottom-to-top arrow overlaps with the chatbot.

### Tasks:
 I'm a GSSOC'24 contributor

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/104766763/0e5d1801-e1b5-40f5-828b-9ecba864caf9)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by karishmaaa101** [comment]
Assign me this issue.

**Comment by Rakesh9100** [comment]
Issue is already opened for this before, pls create new issue or you can comment there if you want to work @karishmaaa101
