### ISSUE TITLE
[Feature] Add Mouse Tracker Card

### ISSUE THREAD

**Issue by hars-21** [Rakesh9100/Beautiify#928]
### Description

A 3D card with mouse tracking on hover effect. It will bend where the mouse points.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new addition
